dare = {
    1: "Let someone draw on your face with a marker.",
    2: "Act like a chicken for one minute.",
    3: "Sing a song chosen by the group with a funny voice.",
    4: "Do your best impersonation of someone in the room.",
    5: "Talk in a foreign accent for the next three rounds.",
    6: "Let someone tickle you for 30 seconds.",
    7: "Wear socks on your hands for the next five minutes.",
    8: "Do an impression of your favorite celebrity.",
    9: "Pretend to be a waiter/waitress and take snack orders from everyone in the group.",
    10: "Talk in an accent for the next three rounds.",
    11: "Imitate a cartoon character until someone guesses who you are.",
    12: "Sing everything you say for the next ten minutes.",
    13: "Give a lap dance to an imaginary person.",
    14: "Let someone else redo your hairstyle.",
    15: "Do a silly dance for one minute without any music.",
    16: "Talk in a high-pitched voice until your next turn.",
    17: "Eat a spoonful of a condiment chosen by the group.",
    18: "Pretend to be a waiter and take snack orders from everyone in the room.",
    19: "Pretend to be a cat and act like one for the next five minutes.",
    20: "Wear underwear on your head for the next three rounds.",
    21: "Sing a song as if you were in a musical.",
    22: "Let someone in the group draw a mustache on your face.",
    23: "Let the group choose an item for you to put in your mouth but not eat.",
    24: "Do your best chicken dance outside on the lawn.",
    25: "Speak in an accent for the next three rounds.",
    26: "Let someone give you a makeover.",
    27: "Wear socks on your hands until your next turn.",
    28: "Do an impression of another player until someone can guess who you are.",
    29: "Dance without music for one minute.",
    30: "Do an impression of your favorite movie scene.",
    31: "Make an animal noise every time someone speaks to you for the next three rounds.",
    32: "Let another player redo your hairstyle.",
    33: "Dance like nobody’s watching for one minute.",
    34: "Let someone in the group put makeup on you.",
    35: "Eat a raw onion slice.",
    36: "Let someone write something embarrassing on your arm with a permanent marker.",
    37: "Act like a mime for the next two rounds.",
    38: "Let another player draw on your face with a marker.",
    39: "Do the worm dance.",
    40: "Talk in a deep voice until your next turn.",
    41: "Let someone else redo your hairstyle and keep it for the rest of the game.",
    42: "Let someone tickle you for one minute.",
    43: "Talk in a British accent until your next turn.",
    44: "Speak in rhymes for the next three rounds.",
    45: "Pretend to be a waiter and take drink orders from everyone in the room.",
    46: "Let someone put lipstick on you.",
    47: "Dance with no music for one minute.",
    48: "Speak in a high-pitched voice for the next three rounds.",
    49: "Let another player draw on your face with a pen.",
    50: "Pretend to be a dog until your next turn.",
    51: "Let someone in the group redo your hairstyle.",
    52: "Act like a baby until your next turn.",
    53: "Talk in an accent chosen by the group until your next turn.",
    54: "Wear socks on your hands until the next round.",
    55: "Do your best runway model walk.",
    56: "Do an impression of someone in the room until someone can guess who it is.",
    57: "Let another player give you a temporary tattoo with a marker.",
    58: "Speak in gibberish for the next three rounds.",
    59: "Act like a monkey until your next turn.",
    60: "Talk like a baby for the next two rounds.",
    61: "Let someone tickle you for 30 seconds.",
    62: "Dance without music until your next turn.",
    63: "Let someone in the group redo your hairstyle and keep it for the rest of the game.",
    64: "Pretend to be a chicken for the next three rounds.",
    65: "Wear underwear over your clothes for the next three rounds.",
    66: "Let someone in the group draw something on your face with a marker.",
    67: "Pretend to be a waiter and take snack orders from everyone in the room.",
    68: "Do your best moonwalk impression.",
    69: "Speak in a foreign accent for the next three rounds.",
    70: "Let someone give you a temporary tattoo with a pen.",
    71: "Act like a monkey until your next turn.",
    72: "Sing everything you say for the next three rounds.",
    73: "Wear socks on your hands until your next turn.",
    74: "Speak in a funny voice until your next turn.",
    75: "Do a funny dance outside where others can see you.",
    76: "Do an impression of your favorite cartoon character.",
    77: "Let someone in the group do your makeup.",
    78: "Talk in a deep voice until your next turn.",
    79: "Do the chicken dance outside for one minute.",
    80: "Wear a hat made of aluminum foil for the next two rounds.",
    81: "Let someone else pick out an outfit for you to wear.",
    82: "Act like a superhero until your next turn.",
    83: "Speak in a robot voice for the next two rounds.",
    84: "Wear a funny hat for the next three rounds.",
    85: "Do your best dance move for the group.",
    86: "Pretend to be a waiter and take food orders from everyone in the room.",
    87: "Act like your favorite celebrity until your next turn.",
    88: "Do your best animal impression until someone guesses the animal.",
    89: "Wear socks on your hands for the next three rounds.",
    90: "Speak in a pirate voice until your next turn.",
    91: "Let someone in the group do your hair.",
    92: "Act like a robot until your next turn.",
    93: "Talk in a funny accent for the next three rounds.",
    94: "Wear a funny hat until the next round.",
    95: "Let someone else pick out a funny outfit for you to wear.",
    96: "Sing a song with your mouth closed.",
    97: "Pretend to be a waiter and take drink orders from everyone in the room.",
    98: "Do a silly dance without music for one minute.",
    99: "Let someone draw on your face with a pen.",
    100: "Act like your favorite movie character until someone guesses who it is."
}
