truth = {
    #question for truth selection>>>>
    1: "What do you fantasize about?",
    2: "What is your biggest fear?",
    3: "What is a secret you’ve never told anyone?",
    4: "Who is your crush?",
    5: "What is the most embarrassing thing you've ever done?",
    6: "What is the most daring thing you've ever done?",
    7: "What is a lie you have told that you regret?",
    8: "What is the last lie you told?",
    9: "Who do you envy and why?",
    10: "What is the most trouble you’ve ever gotten into?",
    11: "What is something you’re glad your family doesn’t know about you?",
    12: "What is the biggest misconception about you?",
    13: "Have you ever been in love?",
    14: "What is your worst habit?",
    15: "What is the most childish thing you still do?",
    16: "What is your guilty pleasure?",
    17: "What is the craziest thing you've done on a dare?",
    18: "What is your most unusual talent?",
    19: "What is the worst thing you've ever said to someone?",
    20: "What is the most awkward date you've ever been on?",
    21: "What is the most expensive thing you’ve stolen?",
    22: "Have you ever cheated on a test?",
    23: "Have you ever pretended to be sick to get out of something?",
    24: "What is the worst gift you have ever received?",
    25: "What is the best gift you’ve ever given?",
    26: "What is the most embarrassing thing in your room?",
    27: "What is the weirdest thing you do when you are alone?",
    28: "Have you ever had a crush on a friend's significant other?",
    29: "What is the most awkward encounter you’ve had with a stranger?",
    30: "What is the worst job you’ve ever had?",
    31: "What is the most annoying thing someone could do on a date?",
    32: "What is the most adventurous thing you’ve done?",
    33: "Have you ever lied about your age?",
    34: "What is the strangest rumor you’ve heard about yourself?",
    35: "What is your biggest pet peeve?",
    36: "What is the most ridiculous thing you’ve done because you were bored?",
    37: "What is the most embarrassing thing you've posted on social media?",
    38: "What is the most immature thing you’ve done in the past year?",
    39: "What is the most inappropriate time you’ve laughed?",
    40: "What is your least favorite family member?",
    41: "What is the most money you’ve spent on something stupid?",
    42: "Have you ever ghosted someone?",
    43: "What is the most ridiculous thing you’ve ever said to someone?",
    44: "What is the most awkward thing you’ve ever worn?",
    45: "What is the most embarrassing nickname you’ve had?",
    46: "Have you ever had an imaginary friend?",
    47: "What is the worst lie you've told to get out of a situation?",
    48: "What is the worst date you’ve been on?",
    49: "What is the weirdest dream you’ve had?",
    50: "What is the longest you’ve gone without showering?",
    51: "What is the worst piece of advice you’ve given?",
    52: "Have you ever broken the law?",
    53: "What is the most ridiculous thing you’ve done for a bet?",
    54: "What is the most embarrassing thing you've been caught doing?",
    55: "What is the most inappropriate crush you've had?",
    56: "What is the biggest secret you've kept from your parents?",
    57: "What is the most embarrassing song you listen to?",
    58: "What is the worst haircut you’ve ever had?",
    59: "What is the most awkward compliment you’ve received?",
    60: "What is the worst prank you've played on someone?",
    61: "What is the most childish thing you’ve done as an adult?",
    62: "What is the most awkward thing you’ve said to your boss?",
    63: "What is the worst advice you've received?",
    64: "What is the most embarrassing thing you've done at a party?",
    65: "What is the most embarrassing email or text you’ve accidentally sent?",
    66: "What is the worst time you’ve been caught in a lie?",
    67: "What is the most awkward thing you've done in front of a crush?",
    68: "What is the most embarrassing thing you've worn in public?",
    69: "What is the strangest habit you have?",
    70: "What is the worst thing you've said in a job interview?",
    71: "What is the most embarrassing thing you've done in front of your family?",
    72: "What is the worst food you’ve ever tasted?",
    73: "What is the most awkward moment you’ve had with a crush?",
    74: "What is the worst gift you’ve ever given?",
    75: "What is the most embarrassing thing you've done while drunk?",
    76: "What is the most ridiculous thing you've done for attention?",
    77: "What is the most awkward place you've fallen asleep?",
    78: "What is the weirdest conversation you’ve had with a stranger?",
    79: "What is the most embarrassing thing you’ve done in front of a large group of people?",
    80: "What is the most awkward thing you've said during a presentation?",
    81: "What is the most embarrassing social media post you've made?",
    82: "What is the worst thing you've done in public?",
    83: "What is the most awkward experience you've had at a restaurant?",
    84: "What is the most inappropriate joke you’ve laughed at?",
    85: "What is the most embarrassing thing you've done at school?",
    86: "What is the most awkward encounter you’ve had with a teacher?",
    87: "What is the worst lie you've been caught in?",
    88: "What is the most ridiculous thing you've done out of jealousy?",
    89: "What is the most awkward moment you’ve had in an elevator?",
    90: "What is the most embarrassing thing you've said to a crush?",
    91: "What is the most awkward thing you've done in an interview?",
    92: "What is the worst time you've been caught off guard?",
    93: "What is the most embarrassing secret you’ve spilled accidentally?",
    94: "What is the most awkward situation you’ve been in?",
    95: "What is the worst time you’ve embarrassed yourself in front of a crush?",
    96: "What is the most awkward moment you've had on a date?",
    97: "What is the worst thing you've done to get someone's attention?",
    98: "What is the most embarrassing thing you've done on a dare?",
    99: "What is the most awkward thing you've done in a crowded place?",
    100: "What is the most embarrassing thing you’ve done while singing along to a song?"
}